apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: public-app
  template:
    metadata:
      labels:
        app: public-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

