apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 0.1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostpath:
    path: /data 
    type: DirectoryorCreate
