apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
