apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ajettesla/app2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: NAME 
            value: AJETTESLA

        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        volumes:
          - name: v-c
            PersistentVolumeClaim: host-pvc
---
  apiVersion: v1
  kind: Service
  metadata:
    name: myapp
  spec:
    selector:
      app: myapp
    ports:
    - port: 80
      targetPort: 3000
    type: LoadBalancer
  
