apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:                 # Optional but good practice
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3             # Add the number of replicas if not defined
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ajettesla/app2:latest
        ports:            # Specify the container port
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app/story
          name: story-volume
      volumes:
      - name: story-volume
        emptyDir: {}      # Corrected spelling of `emptyDir`

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
