apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: example-network-policy
spec:
  podSelector:
    matchLabels:
      app: my-app  # Select pods with the label "app=my-app"
  
  # Apply to both ingress and egress traffic
  policyTypes:
  - Ingress
  - Egress

  # Ingress Rules (incoming traffic)
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend  # Allow traffic from pods with label "role=frontend"
    - namespaceSelector:
        matchLabels:
          name: trusted-namespace  # Allow traffic from pods in the "trusted-namespace"
    - ipBlock:
        cidr: 192.168.0.0/24  # Allow traffic from a specific IP range
        except:
        - 192.168.0.5/32  # Except IP 192.168.0.5

  # Egress Rules (outgoing traffic)
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: backend  # Allow traffic to pods with label "role=backend"
    - namespaceSelector:
        matchLabels:
          name: other-namespace  # Allow traffic to pods in "other-namespace"
    - ipBlock:
        cidr: 10.0.0.0/16  # Allow traffic to a specific IP range
        except:
        - 10.0.1.0/24  # Except traffic to IP range 10.0.1.0/24

  # Optional - Default Deny Ingress and Egress behavior
  # The policy's default behavior is to deny all traffic unless explicitly allowed.

