apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  namespace: default
spec:
  serviceAccountName: pod-access-sa  # Your service account
  containers:
    - name: kubectl
      image: bitnami/kubectl
      command:
        - sleep
        - "3600"  # Keep the pod running for testing
  restartPolicy: Never

