apiVersion: v1
data:
  test: ajettesla
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-19T16:36:26Z"
  name: literalconfigmap
  namespace: default
  resourceVersion: "27306"
  uid: 1f6f4aec-fcd2-403a-8350-218de6a7f086
